### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by szepeviktor** [getzze/Watcher#4]
A Linux daemon should start without a `what-to-do` command.
Please consider `start` as the default command.

**Comment by szepeviktor** [comment]
Typo: `print("Unkown Command")`.

**Comment by getzze** [comment]
I would prefer that calling the daemon without argument returns information about the daemon (if it's running or not), but this is not implemented.

**Comment by szepeviktor** [comment]
I understand your preference. Please consider `start` as the default because all Linux daemons start without `--start`.

**Comment by szepeviktor** [comment]
For example https://sources.debian.net/src/incron/0.5.10-3/debian/init.d/#L34

**Comment by szepeviktor** [comment]
And: https://sources.debian.net/src/nginx/1.6.2-5/debian/nginx-common.nginx.init/#L54-L55

**Comment by getzze** [comment]
In your examples, there is no default command, `start` must be specified.
The python file `watcher.py` is actually like the bash files you show, it calls a deamonify module (`python-daemon`) to launch the program as a daemon, like the start-stop-daemon command.

One can easily write a script using the watcher.py module to implement this default behaviour anyway.

**Comment by szepeviktor** [comment]
Oh! Thank you for the explanation.
So this is the wrong way to write an init script?
https://github.com/szepeviktor/Watcher/commit/38f32f3d2b0e6d71f7285b30db386ff5bc3206e3
I should just prepend

``` bash
### BEGIN INIT INFO
# Provides:          watcher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop Watcher that watches specified files/folders for changes
### END INIT INFO
```

to watcher.py?

**Comment by getzze** [comment]
Use the `watcher.init.d` file, it should work.
